---
abstract: 'SeeAlso handling of International Standard Serial Numbers'
author:
  - 'Thomas Berger C<< <THB@cpan.org> >>'
build_requires: {}
configure_requires:
  Module::Build: 0.35
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SeeAlso-Identifier-ISSN
provides:
  SeeAlso::Identifier::ISSN:
    file: lib/SeeAlso/Identifier/ISSN.pm
    version: 0.5704
requires:
  Business::ISSN: 0
  SeeAlso::Identifier: 0.46
  perl: v5.8.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.5704
